#!/usr/bin/env bash

script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
dry="0"

while [[ $# > 0 ]]; do
    if [[ "$1" == "--dry" ]]; then
        dry="1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute: $@"
    if [[ $dry == "1" ]]; then
        return
    fi

    "$@"
}

log "--------- dev-env ---------"

# Copy Directory

copy_dir() {
    from=$1 
    to=$2
    
    pushd $from > /dev/null || exit 1

    dirs=$(find . -maxdepth 1 -mindepth 1 -type d)
    for dir in $dirs; do
        dir=${dir#./}
        execute rm -rf $to/$dir
        execute cp -r $dir $to/$dir
    done
    popd > /dev/null || exit 1
}

# Copy Files

copy_file() {
    from=$1
    to=$2
    name=$(basename $from)
    execute rm $to/$name 
    execute cp $from $to/$name
}

# copy_dir
copy_dir configs/.config $HOME/.config
copy_dir configs/.config/i3 $HOME/.config/i3
copy_dir configs/.config/i3status $HOME/.config/i3status
copy_dir configs/.local $HOME/.local


copy_file configs/.zshrc $HOME
copy_file configs/.zsh_profile $HOME
copy_file configs/config $HOME/.config/terminator
copy_file configs/.tmux.conf $HOME
copy_file configs/.xinitrc $HOME
copy_file configs/.xprofile $HOME
copy_file configs/.Xresources $HOME


