#!/usr/bin/env bash
set -e

log() { echo "[terminal] $*"; }

KONSOLE_SRC="$DEV_ENV/env/.config/konsole"

log "Installing Konsole"
sudo apt install -y konsole

log "Installing Konsole profile(s)"
mkdir -p "$HOME/.local/share/konsole"

cp -f "$KONSOLE_SRC"/*.profile \
      "$HOME/.local/share/konsole/"

log "Installing konsolerc"
mkdir -p "$HOME/.config"
cp -f "$KONSOLE_SRC/konsolerc" \
      "$HOME/.config/konsolerc"

log "DONE — restart Konsole to apply"

