#!/usr/bin/env bash
set -e

cyan="\e[1;36m"
reset="\e[0m"

status() {
    echo -e "\n${cyan}[tmux]${reset} ${cyan}$1${reset}"
}

# ---------------------------------------------------
# Install tmux
# ---------------------------------------------------
status "Installing tmux"
sudo apt update
sudo apt install -y tmux

# ---------------------------------------------------
# Install TPM
# ---------------------------------------------------
TPM_DIR="$HOME/.tmux/plugins/tpm"

if [[ ! -d "$TPM_DIR" ]]; then
    status "Cloning TPM"
    git clone https://github.com/tmux-plugins/tpm "$TPM_DIR"
else
    status "TPM already installed"
fi


status "Installing tmux plugins"
"$TPM_DIR/bin/install_plugins"

status "Tmux setup complete"

