# Ghostty HackTheBox Theme

palette = 0=#000000
palette = 1=#FF8484
palette = 2=#C5F467
palette = 3=#FFCC5C
palette = 4=#5CB2FF
palette = 5=#CF8DFB
palette = 6=#3A96DD
palette = 7=#c5d1EB
palette = 8=#A4B1CD
palette = 9=#FF8484
palette = 10=#C5F467
palette = 11=#FFCC5C
palette = 12=#5CB2FF
palette = 13=#CF8DFB
palette = 14=#61D6D6
palette = 15=#F2F2F2
background = #141D2B
foreground = #c5d1EB
cursor-color = #FFFFFF
cursor-text = #141D2B
selection-background = #FFFFFF
selection-foreground = #000000

# Black           palette = 0  #000000
# Red             palette = 1  #ff3e3e
# Green (Lime)    palette = 2  #9fef00
# Orange-Yellow   palette = 3  #ffaf00
# Blue (Dark)     palette = 4  #004cff
# Purple          palette = 5  #9f00ff
# Cyan (Mint)     palette = 6  #2ee7b6
# White           palette = 7  #ffffff
# Gray            palette = 8  #666666
# Light Red       palette = 9  #ff8484
# Light Green     palette = 10 #c5f467
# Light Orange    palette = 11 #ffcc5c
# Light Blue      palette = 12 #5cb2ff
# Light Purple    palette = 13 #c16cfa
# Bright Cyan     palette = 14 #5cecc6
# Bright White    palette = 15 #ffffff
