
background = #1C2127
foreground = #B2B2B2
cursor-color = #F8F8F0
selection-background = #3f4750
selection-foreground = #ffffff

# Normal colors
palette = 0=#2e353e
palette = 1=#ec5f66
palette = 2=#99c794
palette = 3=#f9ae58
palette = 4=#5c99d6
palette = 5=#c695c6
palette = 6=#5fb4b4
palette = 7=#a6acb9

# Bright colors
palette = 8=#46525c
palette = 9=#c76b70
palette = 10=#99c794
palette = 11=#fac761
palette = 12=#95b2d6
palette = 13=#c695c6
palette = 14=#87c7c7
palette = 15=#ffffff
