-- ===== rose-pine =====
-- return {
--     "rose-pine/neovim",
--     name = "rose-pine",
--     config = function()
--         require("rose-pine").setup({
--             variant = "auto", -- auto, main, moon, or dawn
--             dark_variant = "main", -- main, moon, or dawn
--             dim_inactive_windows = false,
--             extend_background_behind_borders = true,
--
--             enable = {
--                 terminal = true,
--                 legacy_highlights = true,
--                 migrations = true,
--             },
--
--             styles = {
--                 bold = true,
--                 italic = false,
--                 transparency = false,
--             },
--
--             groups = {
--                 border = "muted",
--                 link = "iris",
--                 panel = "surface",
--
--                 error = "love",
--                 hint = "iris",
--                 info = "foam",
--                 note = "pine",
--                 todo = "rose",
--                 warn = "gold",
--
--                 git_add = "foam",
--                 git_change = "rose",
--                 git_delete = "love",
--                 git_dirty = "rose",
--                 git_ignore = "muted",
--                 git_merge = "iris",
--                 git_rename = "pine",
--                 git_stage = "iris",
--                 git_text = "rose",
--                 git_untracked = "subtle",
--
--                 h1 = "iris",
--                 h2 = "foam",
--                 h3 = "rose",
--                 h4 = "gold",
--                 h5 = "pine",
--                 h6 = "foam",
--             },
--
--             palette = {
--                 -- Override the builtin palette per variant
--                 -- moon = {
--                 --     base = '#18191a',
--                 --     overlay = '#363738',
--                 -- },
--             },
--
--             highlight_groups = {
--                 -- Comment = { fg = "foam" },
--                 -- StatusLine = { fg = "love", bg = "surface", blend = 15 },
--                 -- VertSplit = { fg = "muted", bg = "muted" },
--                 -- Visual = { fg = "base", bg = "text", inherit = false },
--             },
--
--             before_highlight = function(group, highlight, palette)
--                 -- Disable all undercurls
--                 -- if highlight.undercurl then
--                 --     highlight.undercurl = false
--                 -- end
--                 --
--                 -- Change palette colour
--                 -- if highlight.fg == palette.pine then
--                 --     highlight.fg = palette.foam
--                 -- end
--             end,
--         })
--
--         vim.cmd("colorscheme rose-pine")
--         vim.api.nvim_set_hl(0, "Normal",      { bg = "None" })
--         vim.api.nvim_set_hl(0, "NormalFloat", { bg = "None" })
--     end
-- }
-- ====== Sublime =====
--
-- return {
--     {
--         "kaiuri/nvim-juliana",
--         lazy = false,
--         priority = 1000,
--         opts = {}, -- theme has no specific options
--         config = function()
--             vim.cmd("colorscheme juliana")
--
--             vim.api.nvim_set_hl(0, "Normal",      { bg = "None" })
--             vim.api.nvim_set_hl(0, "NormalFloat", { bg = "None" })
--             vim.api.nvim_set_hl(0, "FloatBorder", { bg = "None" })
--             vim.api.nvim_set_hl(0, "SignColumn",  { bg = "None" })
--             vim.api.nvim_set_hl(0, "StatusLine",  { bg = "None" })
--             vim.api.nvim_set_hl(0, "CursorLineNr",  { bg = "None", bold = true }) -- Optional: Transparent number column highlight
--             vim.api.nvim_set_hl(0, "CursorLine",    { bg = "None" })              -- Transparent cursorline
--             --
--             -- Comment color from juliana palette (use fg4 = '#46525c')
--             local comment_color = "#46526C"
--             vim.api.nvim_set_hl(0, "Comment",   { fg = comment_color, italic = false })
--             vim.api.nvim_set_hl(0, "@comment",  { fg = comment_color, italic = false })
--
--         end,
--     },
-- }
--
-- plugins/colorscheme.lua
return {
  {
    "audibleblink/hackthebox.vim",
    lazy = false, -- Load immediately
    priority = 1000, -- High priority for colorschemes
    config = function()
        vim.cmd.colorscheme("hackthebox")
        -- vim.cmd("colorscheme hackthebox")
    end,
  },
}
